library(dplyr)
data <- read.csv("unifiedMLDataMulti.csv",header=TRUE)
names(data)
length(data)
type <- c("b","b","b","d","b","n","b","b","b")
des <- data.frame(V1=as.character(1:length(data)),V2=names(data),V3=type)
filename <- data.frame(V1=c("unifiedMLDataMulti.csv","?","2"), V2=rep("NA",3),V3=rep("NA",3))
des_file <- full_join(filename,des)
write.table(des_file,"description_file.txt",row.names=FALSE, col.names=FALSE,quote=FALSE)
  